### PR TITLE
index title

### PR DESCRIPTION
**Pull request by dimohamdy**
add index number as title on top of each Circle

### CODE REVIEW

**Comment by spromicky** [comment]
Cann't review, cause crash when change `maxCount`. Please keep example project up to date.

**Comment by dimohamdy** [comment]
@spromicky  i test example and i change mac count and no crash happen

**Comment by spromicky** [comment]
@dimohamdy this is a wrong point: disable some of previously enabled features. We must have an ability to change `maxCount` when we want. So bring back please `maxCount` changing in example and fix crash.

**Comment by dimohamdy** [comment]
@spromicky  can you check now ?

**Comment by dimohamdy** [comment]
@spromicky  please check the code now i fix the problem ?

**Comment by spromicky** [comment]
Rewrite it to text layers. Not `UILabel`.

**Pull request closed without merging**
